name: deploy to lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get Runner's IP
        id: runner_ip
        run: ifconfig

      - name: Build and Compress
        run: |
          npm ci && npm run build
          touch nextjs.tar.gz
          tar zcvf nextjs.tar.gz --exclude=nextjs.tar.gz --exclude=.git .

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: get runner ip addresses
        id: ip
        uses: haythem/public-ip@v1.2

      - name: whitelist runner ip address
        run: |
          echo "${{ steps.ip.outputs.ipv4 }}"
          aws lightsail open-instance-public-ports --instance-name Node-js-1 --port-info fromPort=22,toPort=22,protocol=TCP,cidrs=${{ steps.ip.outputs.ipv4 }}/32

      - name: Deploy use SCP
        uses: appleboy/scp-action@master
        with:
          username: bitnami
          host: ${{ secrets.LIGHTSAIL_IP }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "./nextjs.tar.gz"
          target: "/home/bitnami/workspace"

      - name: Reload pm2
        uses: appleboy/ssh-action@master
        with:
          username: bitnami
          host: ${{ secrets.LIGHTSAIL_IP }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/bitnami/workspace
            tar xvf nextjs.tar.gz -U -C nextjs
            rm nextjs.tar.gz
            cd nextjs
            pm2 reload nextjs

      - name: Revoke runner ip address
        run: |
          aws lightsail close-instance-public-ports --instance-name Node-js-1 --port-info fromPort=22,toPort=22,protocol=TCP,cidrs=${{ steps.ip.outputs.ipv4 }}/32
