name: deploy to lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Compress
        run: |
          npm ci && npm run build
          touch nextjs.tar.gz
          tar zcvf nextjs.tar.gz --exclude=nextjs.tar.gz --exclude=.git .

      - name: Deploy use SCP
        uses: appleboy/scp-action@master
        with:
          username: bitnami
          host: ${{ secrets.LIGHTSAIL_IP }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "./nextjs.tar.gz"
          target: "/home/bitnami/workspace"

      - name: Reload pm2
        uses: appleboy/ssh-action@master
        with:
          username: bitnami
          host: ${{ secrets.LIGHTSAIL_IP }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /home/bitnami/workspace
            tar xvf nextjs.tar.gz -U -C nextjs
            rm nextjs.tar.gz
            cd nextjs
            pm2 reload nextjs
